name: garage
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  simple_animations: ^2.2.1
  cloud_firestore: ^0.13.7
  firebase_core: ^0.4.5
  firebase_storage: ^3.1.6
  firebase_auth: ^0.16.1
  grafpix: ^1.2.8

dev_dependencies:
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app-icon/app-logo.png"

  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

 
  assets:

    - assets/designs/avatar.png
    - assets/designs/avatar-up2.png
    - assets/designs/login-intro.png
    - assets/designs/login-intro-landscape.png


    - assets/Icons/normal.png
    - assets/Icons/service.png
    - assets/Icons/left-arrow.png
    - assets/Icons/user.png
    - assets/Icons/computer.png
    - assets/Icons/emergency.png
    - assets/Icons/garage.png
    - assets/Icons/modification.png
    - assets/Icons/parking.png
    - assets/Icons/service_center.png
    - assets/Icons/tyre.png
    - assets/Icons/solo.png
    - assets/Icons/rent.png
    - assets/Icons/hire.png
    - assets/Icons/spare_parts.png
    
    
    - assets/json/main_category.json
    

  
  fonts:
    - family: Schyler
      fonts:
        - asset: assets/fonts/SPro-Black.ttf
        # - asset: assets/fonts/SourceCodePro-Light.ttf
          style: italic

  
  
